#!/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use BapCat\Nom\Compiler;
use BapCat\Nom\Pipeline;
use BapCat\Nom\Transformer;
use BapCat\Persist\Drivers\Local\LocalDriver;

class Pre implements Transformer {
  public function transform($code) {
    return $code;
  }
}

$fs = new LocalDriver(__DIR__);

$cache     = $fs->getDirectory('/cache');
$templates = $fs->getDirectory('/data');

$compiler = new Compiler();
$pre      = new Pre();

$pipeline = new Pipeline($cache, $compiler, [$pre]);
$template = $templates->child['valid.php'];

$code = $pipeline->compile($template);

$out = $cache->child['concurrency-out'];
$out->writeAll($code);
